Docs: Internationalization
GeekHunter-Brasil/hello-world pull request #7
Opened 2022-01-27 19:38 UTC by EEller

2022-01-27 22:44 UTC, pedro-lb approved these changes

2022-01-28 14:47 UTC, pedro-lb requested changes

2022-01-28 14:47 UTC, pedro-lb commented on backend-styleguide/README.md
> +>>>>>>> 6126d4853d255f6b2afee8f229cde6de2b10991b
Merge conflicts

2022-01-28 15:12 UTC, EEller commented on backend-styleguide/README.md
> +>>>>>>> 6126d4853d255f6b2afee8f229cde6de2b10991b
resolve.

2022-01-28 15:32 UTC, pedro-lb approved these changes

2022-01-28 16:32 UTC, VictorSpulveda approved these changes

2022-01-28 19:24 UTC, wesleysiqueira approved these changes

2022-01-28 19:24 UTC, merged